import { mkdir, stat } from "node:fs/promises";
import path from "node:path";

const GENERATOR_INPUT = /^(page\.(tsx|jsx|ts|js)|route\.(ts|js))$/;

function toPosix(file: string) {
  return file.split(path.sep).join("/");
}

export function fileToRoute(file: string) {
  const directory = path.posix.dirname(toPosix(file));
  if (directory === ".") return "/";

  const segments = directory.split("/").map(segment => {
    if (segment.startsWith("[...") && segment.endsWith("]")) return "*";
    if (segment.startsWith("[") && segment.endsWith("]")) {
      return `:${segment.slice(1, -1)}`;
    }
    return segment;
  });

  return `/${segments.join("/")}`;
}

async function scan(directory: string, pattern: string) {
  const glob = new Bun.Glob(pattern);
  const files = await Array.fromAsync(
    glob.scan({ cwd: directory, onlyFiles: true }),
  );
  return files.map(toPosix).sort();
}

async function writeIfChanged(file: string, source: string) {
  const existing = await Bun.file(file)
    .text()
    .catch(() => null);
  // Skipping identical writes keeps mtimes stable so `bun --hot` does not
  // reload the server on every regeneration.
  if (existing !== source) await Bun.write(file, source);
}

export async function generate(root = process.cwd()) {
  const appDirectory = path.join(root, "app");
  const outputDirectory = path.join(root, ".littlecrumb");

  const appStat = await stat(appDirectory).catch(() => null);
  if (!appStat?.isDirectory()) {
    throw new Error(`littlecrumb: app directory not found at ${appDirectory}`);
  }

  const pages = await scan(appDirectory, "**/page.{tsx,jsx,ts,js}");
  const apis = await scan(appDirectory, "**/route.{ts,js}");

  if (pages.length === 0) {
    throw new Error("littlecrumb: no app/**/page.tsx files found");
  }

  const routedPages = pages.map(file => ({ file, route: fileToRoute(file) }));
  const routedApis = apis.map(file => ({ file, route: fileToRoute(file) }));

  const seen = new Map<string, string>();
  for (const { file, route } of [...routedPages, ...routedApis]) {
    const previous = seen.get(route);
    if (previous) {
      throw new Error(
        `littlecrumb: duplicate route ${route} from ${previous} and ${file}`,
      );
    }
    seen.set(route, file);
  }

  for (const { file, route } of routedApis) {
    if (route === "/*") {
      throw new Error(
        `littlecrumb: API route ${file} maps to /* which conflicts with the SPA shell`,
      );
    }
  }

  await mkdir(outputDirectory, { recursive: true });

  const definitions = routedPages.map(({ file, route }) => {
    const importPath = `../app/${file}`;

    return `  {
    path: ${JSON.stringify(route)},
    lazy: async () => adapt(await import(${JSON.stringify(importPath)})),
  }`;
  });

  const routesSource = `// Generated by littlecrumb. Do not edit.
import type { ComponentType } from "react";
import type { RouteObject } from "react-router-dom";

type PageModule = {
  default: ComponentType;
  loader?: RouteObject["loader"];
  action?: RouteObject["action"];
  ErrorBoundary?: ComponentType;
};

function adapt(module: PageModule) {
  return {
    Component: module.default,
    loader: module.loader,
    action: module.action,
    ErrorBoundary: module.ErrorBoundary,
  };
}

export const routes: RouteObject[] = [
${definitions.join(",\n")}
];
`;

  const clientSource = `// Generated by littlecrumb. Do not edit.
import { start } from "littlecrumb/client";
import { routes } from "./routes";

start(routes);
`;

  const htmlSource = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>littlecrumb</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./client.tsx"></script>
  </body>
</html>
`;

  const apiImports = routedApis
    .map(
      ({ file }, index) =>
        `import * as api${index} from ${JSON.stringify(`../app/${file}`)};`,
    )
    .join("\n");

  const apiEntries = routedApis
    .map(
      ({ route }, index) =>
        `    ${JSON.stringify(route)}: handlers(api${index}),`,
    )
    .join("\n");

  const apiHelper = `
const METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"];

type Handler = (request: Bun.BunRequest) => Response | Promise<Response>;

function handlers(module: Record<string, unknown>) {
  return Object.fromEntries(
    METHODS.filter(method => typeof module[method] === "function").map(
      method => [method, module[method]],
    ),
  ) as Record<string, Handler>;
}
`;

  const serverSource = `// Generated by littlecrumb. Do not edit.
import shell from "./index.html";
${apiImports ? `${apiImports}\n` : ""}
const port = Number(process.env.PORT ?? 3000);
${routedApis.length > 0 ? apiHelper : ""}
Bun.serve({
  port,
  routes: {
${apiEntries ? `${apiEntries}\n` : ""}    "/*": shell,
  },
  development: process.env.NODE_ENV !== "production",
});

console.log(\`littlecrumb: http://localhost:\${port}\`);
`;

  await Promise.all([
    writeIfChanged(path.join(outputDirectory, "routes.ts"), routesSource),
    writeIfChanged(path.join(outputDirectory, "client.tsx"), clientSource),
    writeIfChanged(path.join(outputDirectory, "index.html"), htmlSource),
    writeIfChanged(path.join(outputDirectory, "server.ts"), serverSource),
  ]);

  return { pages: pages.length, apis: apis.length, outputDirectory };
}

export function isGeneratorInput(file: string | null) {
  if (!file) return true;
  return GENERATOR_INPUT.test(path.basename(file));
}
