import { mkdir, stat } from "node:fs/promises";
import path from "node:path";

const PAGE_FILE = /^page\.(tsx|jsx|ts|js)$/;

function toPosix(file: string) {
  return file.split(path.sep).join("/");
}

export function fileToRoute(file: string) {
  const directory = path.posix.dirname(toPosix(file));
  if (directory === ".") return "/";

  const segments = directory.split("/").map(segment => {
    if (segment.startsWith("[...") && segment.endsWith("]")) return "*";
    if (segment.startsWith("[") && segment.endsWith("]")) {
      return `:${segment.slice(1, -1)}`;
    }
    return segment;
  });

  return `/${segments.join("/")}`;
}

export async function generate(root = process.cwd()) {
  const appDirectory = path.join(root, "app");
  const outputDirectory = path.join(root, ".bunnext");

  const appStat = await stat(appDirectory).catch(() => null);
  if (!appStat?.isDirectory()) {
    throw new Error(`bunnext: app directory not found at ${appDirectory}`);
  }

  const glob = new Bun.Glob("**/page.{tsx,jsx,ts,js}");
  const pages = (
    await Array.fromAsync(
      glob.scan({
        cwd: appDirectory,
        onlyFiles: true,
      }),
    )
  )
    .map(toPosix)
    .sort();

  if (pages.length === 0) {
    throw new Error("bunnext: no app/**/page.tsx files found");
  }

  const routedPages = pages.map(page => ({
    page,
    route: fileToRoute(page),
  }));

  const seen = new Map<string, string>();
  for (const { page, route } of routedPages) {
    const previous = seen.get(route);
    if (previous) {
      throw new Error(
        `bunnext: duplicate route ${route} from ${previous} and ${page}`,
      );
    }
    seen.set(route, page);
  }

  await mkdir(outputDirectory, { recursive: true });

  const definitions = routedPages.map(({ page, route }) => {
    const importPath = `../app/${page}`;

    return `  {
    path: ${JSON.stringify(route)},
    lazy: async () => adapt(await import(${JSON.stringify(importPath)})),
  }`;
  });

  const routesSource = `// Generated by bunnext. Do not edit.
import type { ComponentType } from "react";
import type { RouteObject } from "react-router-dom";

type PageModule = {
  default: ComponentType;
  loader?: RouteObject["loader"];
  action?: RouteObject["action"];
  ErrorBoundary?: ComponentType;
};

function adapt(module: PageModule) {
  return {
    Component: module.default,
    loader: module.loader,
    action: module.action,
    ErrorBoundary: module.ErrorBoundary,
  };
}

export const routes: RouteObject[] = [
${definitions.join(",\n")}
];
`;

  const clientSource = `// Generated by bunnext. Do not edit.
import { start } from "bunnext/client";
import { routes } from "./routes";

start(routes);
`;

  const htmlSource = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>bunnext</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./client.tsx"></script>
  </body>
</html>
`;

  const serverSource = `// Generated by bunnext. Do not edit.
import shell from "./index.html";

const port = Number(process.env.PORT ?? 3000);

Bun.serve({
  port,
  routes: {
    "/*": shell,
  },
  development: process.env.NODE_ENV !== "production",
});

console.log(\`bunnext: http://localhost:\${port}\`);
`;

  await Promise.all([
    Bun.write(path.join(outputDirectory, "routes.ts"), routesSource),
    Bun.write(path.join(outputDirectory, "client.tsx"), clientSource),
    Bun.write(path.join(outputDirectory, "index.html"), htmlSource),
    Bun.write(path.join(outputDirectory, "server.ts"), serverSource),
  ]);

  return { pages: pages.length, outputDirectory };
}

export function isPageFile(file: string | null) {
  if (!file) return true;
  return PAGE_FILE.test(path.basename(file));
}
